### ISSUE TITLE
Please specify the license for this package

### ISSUE THREAD

**Issue by tarsius** [tesujimath/org-wc#11]
Could you please specify the license used by this package?

Assuming that you want to release under "the GPL v3 or any later version", the best way to do that would be to add this to the library header:

```
;; This file is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 3, or (at your option)
;; any later version.

;; This file is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with this program.  If not, see <http://www.gnu.org/licenses/>.
```

You could also, or instead, add a `LICENSE` file containing the [text of the GPL-3](https://www.gnu.org/licenses/gpl-3.0.txt). But if you only add that file, then the "or (at your option) any later version" bit won't be known.  I recommend that you do *both*.

If this is too noisy for you, then you could also add one of these following lines to the header.  (I do however recommend against doing *only* that - a judge might decide that this is not sufficient.)

```
;; License: GNU General Public License version 3, or (at your option) any later version
;; License: GNU General Public License version 3, or any later version
;; License: GNU GPL version 3, or (at your option) any later version
;; License: GPL version 3, or (at your option) any later version
;; License: GPL version 3, or any later version
;; License: GPL v3, or (at your option) any later version
;; License: GPL v3, or any later version
;; License: GPL-3+
```

**Comment by dato** [comment]
This repo was born from the `org-wc.el` file that Simon Guest sent to the emacs-orgmode mailing list. I just imported it here (see fa2df7b, b540ec3 and f9154e2).

Looking at the subsequent history in this repo, I think only Simon (@tesujimath) can claim copyright.

I’m happy to transfer the repo to him if he’s interested, or to transfer it to any other candidate maintainer after he submits a PR with licensing information. I am not using this package myself any more.

**Comment by tesujimath** [comment]
@dato Yes please transfer the repo to me.  (I should have put it up on github myself initially.)

**Comment by dato** [comment]
I initiated the transfer. You should have received a mail about it, @tesujimath

**Comment by tarsius** [comment]
Thanks!
