### ISSUE TITLE
Cannot set some options

### ISSUE THREAD

**Issue by prosoitos** [tesujimath/org-wc#15]
Thanks for a cool and very useful mode!

I am having a few difficulties though:

1. I would like to ignore subtrees with the `COMMENT` tag, but adding this tag to `org-wc-ignored-tags` has no effect
2. The headings are counted (e.g. `#+OPTIONS:`, `#+TITLE:`, etc.) while the comments in the `org-wc.el` file sound like they shouldn't (and it would be great if they were not counted)
3. I would like to count only the description for any link, but I don't know how to define this in the `org-wc-only-description-link-types`

**Comment by tesujimath** [comment]
@andersjohansson Can you comment on 1 and 3?

For 2, this only affects the total word count shown in the message, I think, since it would be before any heading.  I agree, it should be skipped.  Open to a PR on this, or wait until I have some time to hack on it again.

**Comment by prosoitos** [comment]
For 2: true. But the whole buffer count is actually what I am really interested about :stuck_out_tongue: 

1. In org mode, it is possible to set a `COMMENT` tag to a tree heading. Doing so means that that whole tree will not get exported if the org buffer is converted to pdf or html, etc. So it is equivalent to commenting out a tree, just easier, faster and more convenient (done with one keybinding from anywhere in that tree, regular highlighting remains respected, etc.). Since the tree is commented out though, I would like it not to count for the total word count. (For instance, if I am writing some work with a maximum number of words, I don't want to count a section that will not be exported to my final document)

3. Right now, `org-wc` counts all the words in links. There seems to be an option to set that and the default is to exclude "note". But I don't know how to set this option so that "all" or "any" link would be treated this way. Again, this is about counting words in the actual output: if I have a link to a website with a description, the output will only show the description (hyperlinked). So the actual number of words in the final output document will not include the website path.

**Comment by prosoitos** [comment]
Basically, what I am trying to achieve is to set the options so that the total word count would correspond to the word count of the final document exported to, for instance, html or pdf. Because if I have to write an abstract or whatever with a maximum of x words (limitations in the number of words are very common), counting anything besides this gives me a value that is irrelevant in helping me see where I am at.

**Comment by prosoitos** [comment]
This should actually be part of the default org mode options as it is such a key feature :stuck_out_tongue: . But it is not. And your package is actually the only one I have found in emacs that attempts to do a more refined job than just counting every word indiscriminately. It is very surprising that there aren't many more options... (but maybe I missed some other package?)

**Comment by andersjohansson** [comment]
Some answers (I added some of the advanced settings for links etc. a while back, precisely because I wanted it to count words similar to the output for papers and abstracts etc.)

1. Ignoring commented trees doesn’t work currently. That’s because `COMMENT` is not a tag in org but a special prefix. I more often archive subtrees (in file, with the ARCHIVE tag, `C-c C-x a`), so I didn’t think about that. However, I added the functionality to exclude commented trees in PR #17
2. Links. I see what you are saying and I can see that the options as stated now are cumbersome if you want to set something as the default for unspecified link types.

    Perhaps a more reasonable way would be one option for setting the default for link types which are not specified in any of the other options (which is actually now to count the path, which was what org-wc did before I added some of these options), and then the individual options (as they are now) for link types which need special treatment.

     I’ll think through how this logic could be implemented!

**Comment by andersjohansson** [comment]
@prosoitos, all you asked for is there in #18  ([my branch](https://github.com/andersjohansson/org-wc/tree/default-link-option)). It would be good to get some more testing of the things there. I suppose @tesujimath would also want to test it a bit when there’s time.

**Comment by prosoitos** [comment]
Fantastic!!! Thank you so much! I will test it and let you know if there is anything not behaving as expected.

Thank you so much for your time! and again: congratulations on being the only package (as far as I could find while digging the web) offering a word count that is not indiscriminatory. If your code works well, I think that you should contact the org-mode team and suggest to them that this be included in org as it seems such an essential feature!

Re-the link options: part of the problem for me was not that it was cumbersome, but that I didn't even know how to set the option. It might be my lack of elisp fluency though. And I will see how things are now. But I felt that more documentation on how to write a function for various types of links or a drop-down menu in `*Customize Group: Org wc*` were lacking.

Anyway, thanks again and I'll check #18.

**Comment by prosoitos** [comment]
Thank you very much to the both of you!!! I really appreciate your work on this package! Sorry for my slow comments on @andersjohansson PRs.

This is much better!!! :slightly_smiling_face: :

1/ Points addressed and working great
- the commented areas are not counted
- the commented trees are not counted
- only the link descriptions are counted (not the paths)
- any intro written before the first header is now counted

2/ Things that still make the count different than the word count of the output
- the tree headers themselves are not counted (only the contents are counted)
- the options at the top of the document are counted. By this, I mean all the
```
#+OPTIONS: title:t date:t author:t email:t
#+OPTIONS: toc:t h:6 num:nil |:t todo:nil
#+OPTIONS: *:t -:t ::t <:t \n:t e:t creator:nil
#+OPTIONS: f:t inline:t tasks:t tex:t timestamp:t
#+OPTIONS: html-preamble:t html-postamble:nil

#+PROPERTY: header-args:R :session R:purrr :eval no :exports code :tangle yes :comments link

#+TITLE:   This is my title
#+DATE:	   {{{time(%B %d\, %Y)}}}
#+AUTHOR:  My name
#+EMAIL:   my email
```
etc. 

If you think that you could add the tree headers in the header counts (if you agree with the suggestion of course) and have only the title counted in the entire options section at the top (or nothing at all if having the title is too complicated), then I think that the total count given by `org-wc-display` will be spot on, or in any case, very close to the final count and close enough to be useful when writing pieces that have a word number constraint.

And again: thank you for being the only ones attempting to do this!!!!

(Of course, this won't work with org-babel and code blocks where, depending on the options, the code, the output, none, or both are exported. But having this dialed would be very complicated as it would have to depend on `#+PROPERTY: :exports <code/results/none/both>`. But at least, the package will now allow to get a near-accurate count for any other piece of work, which is fantastic already! :slightly_smiling_face: ).

**Comment by prosoitos** [comment]
Oh, and also, when writing inline code, or using some html or latex formatting, some words are counted that shouldn't. But fixing these finer details is probably a lot of work and they don't throw the count off by near as much as the bigger pictures issues.

One such example: `src_R[:eval no]{purrr}` is counted as 4 words, while it will only be exported as `purrr` (one word). But I don't expect you guys to go over all these situations... If the org team were adopting your code though and were getting at it, I'm sure that it could be done and I think that there would be a lot of value in this...

**Comment by prosoitos** [comment]
Counting the tree headers and excluding the entire top section should be a lot easier though. If you want to make the latter easy, maybe you could code it so that everything above and including the line starting by `#+EMAIL:` is not counted. If you write that in the package description, users are warned to put all of their options above that line (as in my example).

Only little hic is that the title will not be counted, but that is only a few words.

**Comment by prosoitos** [comment]
Note: sorry for giving you guys work! I would be happy to promote your package and/or contact the org team to see if they would like to work with you to make it more sophisticated. I think that it is a really valuable package filling in something that is really missing in org mode.

**Comment by tesujimath** [comment]
My feeling is that all lines starting with `#+` should be excluded.  That is fairly simple, and I think clearly an improvement.  (I'm not sure when I would have time to do it, though, as I am quite busy with other things just now.)

**Comment by andersjohansson** [comment]
@prosoitos, a quick implementation of excluding `#+`-lines. I believe this should work but haven’t actually tested myself yet. Check it out if you want to: https://github.com/andersjohansson/org-wc/tree/exclude-hash-plus

**Comment by prosoitos** [comment]
Thanks!!
