### ISSUE TITLE
Alternative implementation

### ISSUE THREAD

**Issue by alphapapa** [tesujimath/org-wc#20]
Hi,

I forgot about this package when I recently posted https://www.reddit.com/r/emacs/comments/8qm1lb/new_orgcountwords_command/ to /r/Emacs.  I benchmarked the functions just now and you might consider using it instead:

```org
#+BEGIN_SRC elisp
  (with-current-buffer "articles.org"
    (bench-multi
      :forms (("org-word-count" (save-excursion
                                  (call-interactively #'org-word-count)))
              ("ap/org-count-words" (save-excursion
                                      (ap/org-count-words))))))
#+END_SRC

#+RESULTS:
| Form               | x faster than next | Total runtime | # of GCs | Total GC runtime |
|--------------------+--------------------+---------------+----------+------------------|
| ap/org-count-words | 2.56               |   0.060074283 |        0 |              0.0 |
| org-word-count     | slowest            |   0.154041871 |        0 |              0.0 |

#+BEGIN_SRC elisp
  (with-current-buffer "articles.org"
    (save-excursion
      (call-interactively #'org-word-count)))
#+END_SRC

#+RESULTS:
: 2296 words in region.

#+BEGIN_SRC elisp
(with-current-buffer "articles.org"
    (save-excursion
      (call-interactively #'ap/org-count-words)))
#+END_SRC

#+RESULTS:
: Region has 114 lines, 2322 words, and 13334 characters.
```

**Comment by alphapapa** [comment]
Nevermind...

**Comment by tesujimath** [comment]
@alphapapa Is this something for me to consider or not?  I don't really understand the nevermind ;-)

**Comment by alphapapa** [comment]
Well, I found a performance problem after posting this.  I have been profiling it, but I don't know if it's possible to optimize it simply.  As is, it doesn't perform better than the code you have.  My apologies for posting this prematurely and wasting your time.

**Comment by tesujimath** [comment]
@alphapapa No problem, I appreciate you taking the trouble to flag up something which may have been of interest to me.  Let me know if you end up with something worthy of interest ;-)
