### ISSUE TITLE
Wrong type argument with emacs v27.x

### ISSUE THREAD

**Issue by ericsfraga** [tesujimath/org-wc#22]
I just now needed to use org-wc-display after not using it for a long time. The current version does not appear to work with emacs v27 and fairly recent org from git as well. I get the error with backtrace as shown in attached file. This is with `emacs -Q`.

[trace.txt](https://github.com/tesujimath/org-wc/files/4039264/trace.txt)

**Comment by ericsfraga** [comment]
Okay, no worries. If I have some time, I'll see if I can track this down and will let you know.  Thank you.

**Comment by ericsfraga** [comment]
Finally found some time to check this out but the problem has disappeared (in Emacs v28.x as the version number has been upped recently). Your package works very well again!  Thank you.

**Comment by tesujimath** [comment]
You're welcome! 😉
