### ISSUE TITLE
Pair wc with clocksum data?

### ISSUE THREAD

**Issue by Smingvin** [tesujimath/org-wc#30]
Hello,

How could one leverage org-wc to derive word per hour metrics?

I have org-wc showing me the word count in a subtree and storing it as a text property.

I have clock storing time logs for that subtree.

I just want to divide org-wc/clocksum to get wph, either as an overlay or as a table.

Is this feasible?

Srdjan

**Comment by tesujimath** [comment]
It's an interesting idea. I don't know whether you could store a snapshot of the word count on the log, and do a calculation on that.

I don't have time to work on this currently, but if you manage to make something useful I'd be happy to merge it, as long as it doesn't compromise the underlying function, that is mostly speed.

**Comment by Smingvin** [comment]
Understood.

Can you perhaps give me some pointers that come to mind? Where would you look first if you tried to do this?

Srdjan

**Comment by tesujimath** [comment]
I'm sorry I can't really remember anything that would help. I haven't worked on this for so many years I'm afraid! Thanks for your interest.

**Comment by Smingvin** [comment]
No problem. I'll let you know if I have something. In the meantime I'll close this issue.
